//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace x_Lookup_Lite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=atl-va-sql-1a\\p920;Initial Catalog=DVA;User ID=dva;Password=Happy_Tra" +
            "ils")]
        public string DVAConnectionStringFP {
            get {
                return ((string)(this["DVAConnectionStringFP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=mtv-va-sql-1\\p922;Initial Catalog=DVA;User ID=dva;Password=Happy_Trai" +
            "ls")]
        public string DVAConnectionStringMTV {
            get {
                return ((string)(this["DVAConnectionStringMTV"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=mtv-va-sql-1\\p922;Initial Catalog=TurboscanNG_OCR1;User ID=dva;Passwo" +
            "rd=Happy_Trails")]
        public string TurboscanNG_OCR1ConnectionString {
            get {
                return ((string)(this["TurboscanNG_OCR1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=mtv-va-sql-1\\p922;Initial Catalog=TurboscanNG_OCR2;User ID=dva;Passwo" +
            "rd=Happy_Trails")]
        public string TurboscanNG_OCR2ConnectionString {
            get {
                return ((string)(this["TurboscanNG_OCR2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=mtv-va-sql-1\\p922;Initial Catalog=TurboscanNG_OCR3;User ID=dva;Passwo" +
            "rd=Happy_Trails")]
        public string TurboscanNG_OCR3ConnectionString {
            get {
                return ((string)(this["TurboscanNG_OCR3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=mtv-va-sql-1\\p922;Initial Catalog=TurboscanNG_OCR4;User ID=dva;Passwo" +
            "rd=Happy_Trails")]
        public string TurboscanNG_OCR4ConnectionString {
            get {
                return ((string)(this["TurboscanNG_OCR4ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=atl-va-sql-2a\\p921;Initial Catalog=TurboscanNG_ATL-VA-0005;User ID=ib" +
            "ml;Password=ibml123")]
        public string TurboscanNG_ATL_VA_0005ConnectionString {
            get {
                return ((string)(this["TurboscanNG_ATL_VA_0005ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=mtv-va-sql-4\\p1;Initial Catalog=TURBOSCANNG1;User ID=lrmo;Password=Ha" +
            "ppy_Trails")]
        public string TURBOSCANNG1ConnectionString {
            get {
                return ((string)(this["TURBOSCANNG1ConnectionString"]));
            }
        }
    }
}
